version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: todo_server_1
      APP_PORT: 5173
      PROXY_AUTH_ADD: "false"

  app:
    image: carlosfallen/todo:v2.0.2
    restart: on-failure
    environment:
      - NODE_ENV=production  # Ambiente de produção
    ports:
      - "5173:5173"  # Frontend (Vite)
      - "3001:3001"  # Backend (Node.js)
    volumes:
      - ${APP_DATA_DIR}:/app/data  # Armazenamento persistente (CRÍTICO)
      - ${UMBREL_ROOT}/data/storage:/storage  # Acesso a arquivos do Umbrel (opcional)
    ports:
      - 5173:5173
      - 3001:3001
